# Pre-class Reading: Day 10 (Oct 12, 2023)<br>Introduction to NumPy arrays
Learning goals
1. Identify the rank, number of rows, number of columns and length for a given numpy array.
1. Identify the attributes ndim, shape, size and dtype for a given numpy array.
1. Predict the output from combining two numerical numpy arrays of the same shape using the common arithmetic operations `+`, `-`, `/`, and `*`.
1. Define (create) an array with one or more dimensions and fill it with values provided via a list (e.g., `numpy.array([1, 2, 3])`).
1. Use an intrinsic array creation function to define an array and fill it with zeros or ones (e.g., `numpy.zeros(3)`).
1. Specify data type when creating a numpy array (e.g., `np.array([1, 2, 3],dtype=float)`).
1. Index or slice a numpy array having one or more dimensions. 
1. Use array methods such as `sum()`, `max()` and `std()` to perform operations on arrays

## *Self-assessment questions*

**If you can already answer these correctly, you can skip the rest of the reading assignment and submit it. Otherwise, complete the rest of the reading assignment and return to these questions to test what you learned. You might decide you would benefit from further review before class.**

Note that these questions can often be answered easily by running the provided code, so the intellectual work on your part is figuring out the correct answer and then running the code to check your answer.

Please ensure all of these self-assessment questions are answered correctly before submitting this pre-class reading assignment. The *Your Turn* questions, found throughout the rest of this assignment, are for your practice as you learn this material and do not need to be answered correctly to receive full completion marks for this pre-class reading assignment.

### Self-assessment question 10.1

What will the following code print?
```python
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.ndim(a))
```
A) 1<br>
B) 2<br>
C) 3<br>
D) 9<br>

In [ ]:
# Code testing area to help answer this question



In [ ]:
# Enter your answer inside the string quotes and run this cell to check your anwer

answer = ""

import hashlib
assert answer in ['A', 'B', 'C', 'D'], "Your answer did not match any of the choices"
assert hashlib.sha256(answer.encode()).hexdigest() == \
    'df7e70e5021544f4834bbee64a9e3789febc4be81470df629cad6ddb03320a5c', "Your answer is incorrect"
print("Your answer", answer, "is correct") # Passed all assert statements above

### Self-assessment question 10.2

What will the variable C contain after running the following code?

```python
import numpy as np
A = np.array([[9, 1], [4, 2]])
C = np.zeros(np.size(A))
```

A) A list of four zeros<br>
B) A one-dimensional numpy array of four integer zeros<br>
C) A one-dimensional  numpy array of four floating point zeros<br>
D) A three-dimensional numpy array containing a total of 72 floating point zeros<br>
E) A two-dimensional numpy array containing a total of 4 floating point zeros.

In [ ]:
# Code testing area to help answer this question



In [ ]:
# Enter your answer inside the string quotes and run this cell to check your anwer

answer = ""

import hashlib
assert answer in ['A', 'B', 'C', 'D', 'E'], "Your answer did not match any of the choices"
assert hashlib.sha256(answer.encode()).hexdigest() == \
    '6b23c0d5f35d1b11f9b683f0b0a617355deb11277d91ae091d399c655b87940d', "Your answer is incorrect"
print("Your answer", answer, "is correct") # Passed all assert statements above

### Self-assessment question 10.3

What is printed by this array operation?

```python
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A*B)
```

A) `32`<br>
B) `[5 7 18]`<br>
C) `[4 10 18]`<br>
D) `[12 10 4]`<br>
E) `15`

In [ ]:
# Code testing area to help answer this question



In [ ]:
# Enter your answer inside the string quotes
# and run this cell to check your anwer

answer = ""  

import hashlib
assert answer in ['A', 'B', 'C', 'D', 'E'], "Your answer did not match any of the choices"
assert hashlib.sha256(answer.encode()).hexdigest() == \
    '6b23c0d5f35d1b11f9b683f0b0a617355deb11277d91ae091d399c655b87940d', "Your answer is incorrect"
print("Your answer", answer, "is correct") # Passed all assert statements above

### Self-assessment question 10.4

What output will the following code produce?

```python
import numpy as np
A = np.array([[9,1],[4,2]])
X = np.sqrt(np.sort(A))
print(X)

# A
[[1. 2.]
[1.41421356 3.]]

# B
[[1. 1.41421356]
[2. 3.]]

# C
[[1. 3.]
[1.41421356 2.]]

# D
[[1. 1.41421356]
[3. 2.]]

# E
[1., 1.41421356, 2., 3.]
```

In [ ]:
# Code testing area to help answer this question



In [ ]:
# Enter your answer inside the string quotes
# and run this cell to check your anwer

answer = ""  

import hashlib
assert answer in ['A', 'B', 'C', 'D', 'E'], "Your answer did not match any of the choices"
assert hashlib.sha256(answer.encode()).hexdigest() == \
    '6b23c0d5f35d1b11f9b683f0b0a617355deb11277d91ae091d399c655b87940d', "Your answer is incorrect"
print("Your answer", answer, "is correct") # Passed all assert statements above

### Self-assessment question 10.5

What will be the output of the following?

```python
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print( A[:, 1] )
```
A) `[1, 4, 7, 10]` <br>
B) `[2, 5, 8, 11]` <br>
C) `[1, 2, 3]` <br>
D) `[4, 5, 6]` <br>

In [ ]:
# Code testing area to help answer this question



In [ ]:
# Enter your answer inside the string quotes
# and run this cell to check your anwer

answer = ""  

import hashlib
assert answer in ['A', 'B', 'C', 'D', 'E'], "Your answer did not match any of the choices"
assert hashlib.sha256(answer.encode()).hexdigest() == \
    'df7e70e5021544f4834bbee64a9e3789febc4be81470df629cad6ddb03320a5c', "Your answer is incorrect"
print("Your answer", answer, "is correct") # Passed all assert statements above

## *10.1 Introduction to NumPy*

The fundamental library needed for scientific computing with Python is called NumPy.
This __Open Source__ library contains:

- A powerful N-dimensional array object;
- Advanced array slicing methods (to select array elements); and
- Convenient array reshaping methods.

It also contains libraries with numerical routines, including:

* Basic linear algebra functions;
* Fourier transforms; and
* Sophisticated random number capabilities.

Class 10 is about learning how to create and manipulate arrays and using some of the most common methods applied to arrays. We’ll look at some more advanced array and NumPy concepts later in the course.

## *10.2 Overview of NumPy arrays*

NumPy's main object is the homogeneous multidimensional array called ndarray.  Homogeneous here means that every element of the array has the same type (i.e., an array of ints, floats or complex values).

* An array is a table of elements (usually numbers), all of the same type, indexed by one or more non-negative integers. Typical examples of multidimensional arrays include vectors, matrices, images and spreadsheets, but are not limited to these.
* The array can have multiple dimensions, also called _axes_. The number of axes is also known as the _rank_.

The link below should take you to the NumPy section of this webpage, where you will read up to, but not including the subsection Broadcasting (a concept we will cover later). This means you will read the subsections Arrays, Array Indexing, Datatypes, and Array Math.

* http://cs231n.github.io/python-numpy-tutorial/#numpy

## *10.3 Some array examples*
Before executing this code, see if you can figure out what to expect as the output.

In [ ]:
# Run me!

import numpy
a = numpy.array([1,3,5,7,9])
b = numpy.array([3,5,6,7,9])
c = a + b
print(c)

You might be asking youtself, why are there two (different) sets of brackets when creating each of the arrays, e.g., `a = numpy.array([1, 3, 5, 7, 9])`?

The `numpy.array()` function attempts to turn the argument it is given into an array. The: `[1, 3, 5, 7, 9]` is a python list, which we have already seen. Lists and arrays have a number of things in common, but arrays have many additional useful features not available when working with lists.

### `import numpy as np`
Instead of typing `numpy` every time we use an array, it is common to rename it, e.g. as `np` with the following modified import command:

In [ ]:
# Run me!

import numpy as np
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9])
c = a + b
print(c)

You should always import `numpy` this way.

## *10.4 The meaning of rank, row, column, length and axis*

Let's start with a couple of examples to highlight how some of this terminology is used

* `[7, 5, -1]`: An array of rank 1 i.e. It has 1 axis of length 3
* `[ [ 1.5, 0.2, -3.7], [ 0.1, 1.7, 2.9] ]`: An array of rank 2, meaning that it has two axes (two rows and three columns). The first is of length 2 and the second of length 3. 

### NumPy array attributes
Every array has a number of attributes that describe the array or the data it holds. These attributes include:

* `ndarray.ndim`: the number of axes (dimensions) of the array i.e. the rank.
* `ndarray.shape`: the dimensions of the array – the lengths along each of the axes.
* `ndarray.size`: the total number of elements of the array, equal to the product of the elements of shape.
* `ndarray.dtype`: an object describing the type of the elements in the array. One can create or specify dtypes using standard Python types. NumPy also provides many types, for example bool, int8, int16, int32, int64, float16, float32, float64, float128, complex64, complex128. The numerical parts of these names indicate how many “bits” are used to store the number. Larger numbers indicate that larger values that can be stored in the data type, and for floats, with higher precision.
* `ndarray.itemsize`: the size in bytes of each element of the array. E.g. for elements of type float64, itemsize is 8 (=64/8), while complex32 has itemsize 4 (=32/8) (equivalent to ndarray.dtype.itemsize).
* `ndarray.data`: the buffer containing the actual elements of the array. Normally, we won't need to use this attribute because we will access the elements in an array using indexing facilities.

Some examples of attributes of the array `a` from earlier:

In [ ]:
# Run me (and the other cells below)!
# I use an array created in the previous section

a

In [ ]:
a.ndim # equivalent to np.ndim(a)

In [ ]:
a.shape # or np.shape(a)

In [ ]:
a.size

In [ ]:
a.dtype

In [ ]:
a.itemsize

In [ ]:
a.data

## *10.5 NumPy array creation and use*
Let's again use some examples, in this case to highlight array creation and use:

In [ ]:
# Run me (and the other cells below)!

import numpy as np
# Creates a 2-dimensional array
a = np.array([[1, 2, 3], [3, 6, 9], [2, 4, 6]])  

In [ ]:
a

In [ ]:
a.ndim  # check attribute ndim

In [ ]:
print(a[0, :])  # prints the first row

The notation above is similar to what we saw for strings and lists, but for two dimensional arrays you can provide two indicies, separated by a comma, such as `a[0, 1]` or `a[0:1, 0:2]`

In [ ]:
# Run me (and the other cells below)!

print(a[1, 2])  # prints an element of the array

In [ ]:
print(a[1, 1:3])  # and slices

In [ ]:
print(a[:, 1])  # prints the second column

Consider what you think the two arrays `b` and `c` will be...

In [ ]:
# Try it!
import numpy as np
b = np.ones(10)
c = np.zeros((2,3), dtype=np.complex)

# Use some code here to see what arrays b and c look like


## *10.6 NumPy array methods*
There are many functions in `numpy` that can manipulate or perform calculations on arrays. Examples using the (2d) array `a` from above:

In [ ]:
# Run me (and the other cells below)!
# I continue to use previously defined arrays

a

In [ ]:
a.sum()

In [ ]:
a.mean()

In [ ]:
a.std() # standard deviation

In [ ]:
a.max()

In [ ]:
a.min()

An exhaustive list of numpy methods can be found at:

* http://docs.scipy.org/doc/numpy/reference/routines.html

Have a look at to see what's there, but don't spend a long time reading about them all – the list is very, very long!

## *10.7 NumPy mathematics*
You can use the conventional operators +, -, /, * for numpy arrays. You can also use methods for mathematical operations:

In [ ]:
# Run me!

# Addition is element by element
import numpy as np
F = np.array([1,2,3])
G = np.array([4,5,6])
print(F + G)

In [ ]:
# Run me!

# We can do mathematical operations on an entire array at once
import numpy as np
H = 3 * F
print(H)

In [ ]:
# Run me!

np.sqrt(a)

In [ ]:
# Run me!

x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

### math vs numpy:
You may remember we mentioned last time that functions like sin, cos, tan, exp, etc. are available in both the math module and in numpy as the numpy versions are more flexible. The math module functions will not work on a numpy array.

### Array mathematics can simplify many of the things we have been doing with lists

Below is our Euler's method code from Solo Worksheet 09. We highlight some changes (`### NEW ARRAY STUFF ###`) that make the residuals calculations look much simpler. Also note that all of our graphs can use lists or arrays for their plotting variables.

In [ ]:
def euler(y, v, t, t_end, t_step):
    """Euler's method integrator
    Args:
    - y: initial height
    - v: initial y-velocity
    - t, t_end: start and end time
    - t_step: step size
    Returns: list of times and corresponding y values
    """
    t_list = [t]
    y_list = [y]
    v_list = [v]
    a = -9.81  # gravitational acceleration
    
    while t < t_end:
        y = y + t_step * v
        v = v + t_step * a
        t = t + t_step

        y_list.append(y)
        v_list.append(v)
        t_list.append(t)
        
    return t_list, y_list

## Main part of the program
import numpy as np
import matplotlib.pyplot as plt

y0, v0 = 0, 10  # Initial position and velocity
t0, tmax, dt = 0, 2, 0.1  # Start, end times and step size

# Euler solution
times, y_euler = euler(y0, v0, t0, tmax, dt)


### NEW ARRAY STUFF ###

# Convert the returned lists to numpy arrays
times = np.array(times)
y_euler = np.array(y_euler)

# Exact solution at the same times as Euler solution
# - Because of array math, 'y_exact' will be the same length as 'time'
#   and each element will be calculated with respect to what was contained in
#   that element in 'times'
y_exact = y0 + v0*times - 0.5*9.81*times**2

# Residuals using numpy arrays
# - We only have to subtract one array from the other to get residuals!
residuals_euler = y_euler - y_exact


### ALL OF THE PLOTTING STILL WORKS WITH ARRAYS ###

# Create figure and subplots
fig, ax = plt.subplots(nrows=2, ncols=1, figsize=(10, 8))

# Main plot (Euler's method vs Exact solution)
ax[0].plot(times, y_exact, 'r--', label='Exact Solution' ) 
ax[0].plot(times, y_euler, 'b', label="Euler's method" )
ax[0].set_title("One-dimensional motion")
ax[0].set_xlabel("t (s)")
ax[0].set_ylabel("y (m)")
ax[0].legend()
ax[0].grid(True)

# Residuals subplot
ax[1].plot(times, residuals_euler, 'b', label="Euler's method" )
ax[1].set_xlabel("t (s)")
ax[1].set_ylabel("Residual (m)")
ax[1].legend()
ax[1].grid(True)

plt.tight_layout()
plt.show()

## *10.8 Further optional reading*
http://freecomputerbooks.com/Computational-Physics-with-Python-by-Eric-Ayars.html
* There is a (very) short introduction to numpy in section 3.0 of the book mentioned last day. On that website find the 'Read and Download Links' section. Click on 'Computational Physics with Python (Eric Ayars)'. Again, material in that book is presented in a very different order from our approach.


## *Submitting this reading assignment*
Before submitting your work, restart + rerun your notebook to make sure that your self-assessmet questions run correctly and without error. We will only check that the Self-assessment questions at the start of the assignment have run correctly. After you've executed and checked your notebook, choose: File >> Save_and_Export_Notebook_As >> HTML. This will download an HTML version of your notebook to your computer which you can upload to Canvas